version: 0.2
        
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo install

  pre_build:
    commands:
      - echo post build
      - command
  build:
    commands:
      - mvn package
      - echo build success

  post_build:
    commands:
      - echo post build
artifacts:
  files:
    - target/spring-boot-todo-rest-api-h2-aws-pileline-0.0.1-SNAPSHOT.jar
